"""r16 rebrand: no desk draws the old "UW ___ Desk" name any more; each takes "<brand> · <desk>" from the
dashboard (window.UWBrand in the page, brandname.py on the server) and still credits Unusual Whales as the
data source.

    python -m unittest test_brand
"""
import hashlib
import os
import re
import subprocess
import sys
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
PAGES = {"Valuation Desk/index.html": 'uwLabel("Valuation Desk")',
         "Confluence Desk/index.html": 'uwLabel("Confluence Desk")',
         "Institutional Desk/index.html": "uwLabel(SHARE_META.brand)",
         "Swing Desk/index.html": 'uwLabel("Swing Desk")',
         "UW Flow Desk/body.html": "uwLabel('Unusual Options Flow')",
         "Growth Desk/index.html": 'uwLabel("Growth Leaders")'}
SERVER_SIDE = ["Valuation Desk", "Confluence Desk", "Swing Desk", "Growth Desk"]
OLD = re.compile(r"UW (Valuation|Confluence|Institutional|Swing|Unusual Flow) Desk")


def read(rel):
    with open(os.path.join(HERE, rel), encoding="utf-8") as fh:
        return fh.read()


class Rebrand(unittest.TestCase):
    def test_pages_draw_the_dashboard_name_and_credit_the_data(self):
        for rel, call in PAGES.items():
            with self.subTest(rel):
                page = read(rel)
                self.assertIn(call, page)
                self.assertIn("function uwLabel(fb)", page)
                self.assertIn("data-uw-name", page)
                self.assertIn("Unusual Whales", page)                   # the data credit stays
                code = re.sub(r"/\*.*?\*/", "", page, flags=re.S)
                self.assertIsNone(OLD.search(code), rel)

    def test_server_side_outputs_use_brandname(self):
        digests = set()
        for d in SERVER_SIDE:
            with self.subTest(d):
                digests.add(hashlib.sha256(read(d + "/brandname.py").encode()).hexdigest())
        self.assertEqual(len(digests), 1, "brandname.py differs between desks")
        for rel in ("Valuation Desk/generate.py", "Valuation Desk/docxw.py", "Confluence Desk/notify.py",
                    "Swing Desk/notify.py"):
            with self.subTest(rel):
                code = "\n".join(l for l in read(rel).splitlines() if not l.lstrip().startswith("#"))
                self.assertIsNone(OLD.search(code.split('"""', 2)[-1]), rel)
        self.assertIn('brandname.label("valuation"', read("Valuation Desk/generate.py"))
        self.assertIn('brandname.label("confluence"', read("Confluence Desk/notify.py"))
        self.assertIn('brandname.label("swing"', read("Swing Desk/notify.py"))
        self.assertIn("Data: Unusual Whales", read("Swing Desk/notify.py"))
        self.assertIn("Data: Unusual Whales", read("Confluence Desk/notify.py"))

    def test_a_hostile_name_cannot_break_out_of_the_generated_script(self):
        """The desk name lands in the generated script's docstring, and the desk RUNS that script."""
        src = read("Valuation Desk/generate.py")
        m = re.search(r"desk = re\.sub\((r'[^']*'), \"\", brandname\.label\(\"valuation\"", src)
        self.assertTrue(m, "generate.py must strip the desk name before it goes into the script")
        pattern = eval(m.group(1))
        clean = re.sub(pattern, "", 'Evil"""; import os #\\')
        self.assertNotIn('"', clean)
        self.assertNotIn("\\", clean)
        q3 = "'" * 3
        head = src.split("SCRIPT_HEAD = " + q3, 1)[1].split(q3, 1)[0]
        out = head.format(desk=clean, ticker="ACME", stamp="now", version="v", fname="f.py")
        self.assertEqual(out.count('"""'), head.count('"""'))      # the docstring still closes where it did
        self.assertIn("generated by Evil; import os # on now", out)


if __name__ == "__main__":
    unittest.main()
