"""
The three deliverables the brief asks for, per ticker per run:

    {TICKER}_analysis.py            standalone, re-runnable, stdlib only
    {TICKER}_Valuation_Analysis.docx
    {TICKER}_Summary_Card.png       drawn by the browser (index.html), POSTed back

plus {TICKER}_console.txt (the script's own output, captured by EXECUTING it,
per Step 3) and {TICKER}_data.json (the raw payloads, for audit).

The analysis script inlines valuation.py and the raw payloads. Executing it is
not a formality: its printed verdict is compared with the in-process verdict,
so a script that would not reproduce the report fails the run loudly.
"""

import json
import os
import re
import subprocess
import sys
from datetime import datetime

import brandname
import valuation as V
from docxw import Doc, run as R, INK2, INK3

HERE = os.path.dirname(os.path.abspath(__file__))
GREEN, YELLOW, RED = "0CA30C", "C98500", "D03B3B"


def colour_hex(key):
    return {"good": GREEN, "warn": YELLOW, "bad": RED}.get(key, INK2)


def names(ticker):
    t = re.sub(r"[^A-Z0-9.\-]", "", ticker.upper())
    return {"py": "%s_analysis.py" % t, "docx": "%s_Valuation_Analysis.docx" % t,
            "png": "%s_Summary_Card.png" % t, "console": "%s_console.txt" % t,
            "data": "%s_data.json" % t}


# ------------------------------------------------------------------ script

SCRIPT_HEAD = '''#!/usr/bin/env python3
"""
{ticker} valuation -- generated by {desk} on {stamp}.

Self-contained: the model (valuation.py {version}) and the Unusual Whales
payloads it was run on are both embedded below, so this file reproduces
exactly the numbers in {ticker}_Valuation_Analysis.docx, on any machine with
Python 3 and nothing else installed.

    python {fname}              print the full analysis
    python {fname} --json       print the result as JSON
    python {fname} --discount 0.09 --growth 0.20   re-run with overrides

Educational use only. Not financial advice.
"""
'''

SCRIPT_TAIL = '''

# ======================================================================
# embedded run
# ======================================================================

PAYLOADS = json.loads({payloads!r})
FX = json.loads({fx!r})
OVERRIDES = json.loads({overrides!r})

if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--discount", type=float)
    ap.add_argument("--growth", type=float)
    a = ap.parse_args()
    ov = dict(OVERRIDES)
    if a.discount is not None:
        ov["discount"] = a.discount
    if a.growth is not None:
        ov["growth"] = a.growth
    res = run(PAYLOADS, fx=FX, overrides=ov)
    if a.json:
        print(to_json(res))
    else:
        print(console_report(res))
'''


# The model source is snapshotted ONCE, at import -- i.e. the exact code this
# process is running. Reading it from disk per run meant a file updated while
# the desk was running produced a script with DIFFERENT code from the server's
# in-memory model, and the self-check refused the run (the server had the old
# rounding, the script had the new half-up rounding -> scores one point apart).
_MODEL_SRC = open(V.__file__, encoding="utf-8").read()


def analysis_script(res, payloads, fx=None):
    src = _MODEL_SRC
    body = src.split('"""', 2)[2]          # drop the module docstring, keep the code
    # The ticker lands inside the generated script, which the desk then RUNS. It comes from UW's data,
    # so it is reduced to ticker characters first: a hostile "symbol" could otherwise close the
    # docstring and execute code (2026-09-26 security review).
    t = re.sub(r"[^A-Z0-9.\-]", "", str(res["fin"]["ticker"]).upper())[:12] or "TICKER"
    # The desk name comes from the dashboard's Settings and lands in a docstring: no quotes or backslashes.
    desk = re.sub(r'["\\\\]', "", brandname.label("valuation", "Valuation Desk")) or "Valuation Desk"
    head = SCRIPT_HEAD.format(desk=desk, ticker=t, stamp=datetime.now().strftime("%Y-%m-%d %H:%M"),
                              version=V.MODEL_VERSION, fname=names(t)["py"])
    tail = SCRIPT_TAIL.format(payloads=json.dumps(payloads, separators=(",", ":")),
                              fx=json.dumps(fx or {}), overrides=json.dumps(res.get("overrides") or {}))
    return head + body + tail


def execute_script(path, timeout=60):
    """Run the generated script with THIS interpreter; return stdout."""
    proc = subprocess.run([sys.executable, path], capture_output=True, text=True,
                          timeout=timeout, encoding="utf-8", errors="replace",
                          env=dict(os.environ, PYTHONIOENCODING="utf-8"))
    if proc.returncode != 0:
        raise RuntimeError("%s exited %d: %s" % (os.path.basename(path), proc.returncode,
                                                  (proc.stderr or "").strip()[-600:]))
    return proc.stdout


def verify_console(res, text):
    """The executed script must reproduce the in-process verdict and base value."""
    want = "VERDICT: %s/10 %s" % (res["score"]["badge"], res["score"]["verdict"])
    if want not in text:
        raise RuntimeError("Generated script did not reproduce the verdict (%s). If the desk "
                           "was updated while running, close the desk window and start it "
                           "again with START_HERE.bat." % want)
    base = V.px(res["valuation"]["scenarios"]["base"]["per_share"])
    if base not in text:
        raise RuntimeError("Generated script did not reproduce the base value %s." % base)


# ------------------------------------------------------------------ report

def report(res, path, stamp=None):
    f, v, s, m = res["fin"], res["valuation"], res["score"], res["multiples"]
    sc = v["scenarios"]
    b = sc["base"]
    col = colour_hex(s["colour"])
    stamp = stamp or datetime.now().strftime("%B %d, %Y")
    desk = brandname.label("valuation", "Valuation Desk")
    doc = Doc(title="%s Valuation Analysis" % f["ticker"], author=desk,
              footer="%s valuation - %s - Data: Unusual Whales API - Educational use only, "
                     "not financial advice." % (f["ticker"], stamp))

    # 1 ------------------------------------------------------------- title
    doc.title("%s Valuation Analysis" % f["ticker"],
              "%s  |  %s  |  %s  |  data basis %s" % (f["name"], f["sector"], stamp, f["basis"]))
    doc.callout([R("%d/10  %s" % (s["badge"], s["verdict"]), bold=True, color=col, size=16),
                 R("\n" + res["thesis"], bold=True, size=11)], col)
    doc.h1("1. Executive Summary")
    desc = f["description"].rstrip(". ") if f["description"] else ""
    desc = desc.replace("...", "").rstrip(" ,.")
    if desc:
        desc = desc[0].upper() + desc[1:]
    doc.p("%s is a %s company trading at %s with a market cap of %s. %s%s Base case DCF "
          "valuation suggests intrinsic value of %s per share, implying %s %s from the "
          "current price."
          % (f["name"], f["sector"].lower(), V.px(f["price"]), V.money(f["marketcap"]),
             (desc + ". ") if desc else "",
             "Revenue is %s on a %s basis, %s year on year." % (
                 V.money(f["revenue"]), f["basis"], V.signed_pct(f["rev_growth"])),
             V.px(b["per_share"]), V.pct(abs(b["upside"] or 0)),
             "upside" if (b["upside"] or 0) >= 0 else "downside"))
    doc.p([R("VERDICT: ", bold=True), R("%s — " % s["verdict"], bold=True, color=col),
           R("%s. %s" % (res["key_driver"][0].upper() + res["key_driver"][1:], res["class_reason"]))])
    doc.p([R("Key insight: ", bold=True), R(_insight(res))])
    if _synopsis(res):
        doc.p([R("In a tweet: ", bold=True), R(_synopsis(res), italic=True)])
    if res.get("why"):
        doc.h2("Why this verdict")
        for line in res["why"]:
            doc.bullet(R(line))

    # 2 ------------------------------------------------------ key metrics
    doc.h1("2. Key Metrics")
    rows = [["Metric", "Value", "Metric", "Value"],
            ["Current price", V.px(f["price"]), "Revenue (%s)" % f["basis"].split(" to ")[0], V.money(f["revenue"])],
            ["Intrinsic value (base)", V.px(b["per_share"]), "Revenue growth YoY", V.signed_pct(f["rev_growth"])],
            ["Upside / downside", V.signed_pct(b["upside"]), "Operating margin", V.pct(f["op_margin"])],
            ["Market cap", V.money(f["marketcap"]), "Net margin", V.pct(f["net_margin"])],
            ["Shares outstanding", "%.1fM" % ((f["shares"] or 0) / 1e6), "Free cash flow", V.money(f["fcf"])],
            ["Beta", "n/a" if f["beta"] is None else "%.2f" % f["beta"], "Cash + ST investments", V.money(f["liquid"])],
            ["Score", "%.1f / 10" % s["score"], "Total debt (incl. leases)", V.money(f["debt"])]]
    colors = {(3, 1): GREEN if (b["upside"] or 0) >= 0 else RED, (7, 1): col}
    doc.table(rows, [2600, 2440, 2600, 2440], align=["left", "right", "left", "right"], colors=colors)

    # 3 ------------------------------------------------- business quality
    doc.h1("3. Business Quality Assessment")
    doc.table([["", f["basis"], "Prior year"],
               ["Revenue", V.money(f["revenue"]), V.money(f["prev_revenue"])],
               ["Operating margin", V.pct(f["op_margin"]), V.pct(f["prev_op_margin"])],
               ["Gross profit", V.money(f["gross_profit"]), ""],
               ["EBITDA (operating income + D&A)", V.money(f["ebitda"]), ""],
               ["Net income", V.money(f["net_income"]), ""]],
              [4400, 2840, 2840], align=["left", "right", "right"])
    gtxt = ("Revenue grew %s year on year%s. " % (V.signed_pct(f["rev_growth"]),
            (" and %s quarter on quarter" % V.signed_pct(f["q_growth"])) if f["q_growth"] is not None else ""))
    if f["op_margin"] is not None and f["prev_op_margin"] is not None:
        gtxt += "Operating margin moved from %s to %s -- %s. " % (
            V.pct(f["prev_op_margin"]), V.pct(f["op_margin"]),
            "improving" if f["op_margin"] > f["prev_op_margin"] else "deteriorating")
    if not res["multiples"]["pe_meaningful"]:
        gtxt += ("Net income is not a reliable guide here: with an operating loss, reported "
                 "earnings are dominated by non-operating items, so P/E is not used. ")
    doc.p(gtxt)
    q = res.get("quality")
    if q:
        doc.h2("Quality & management score: %s" % ("%.1f / 10 (%s)" % (q["score"], q["tier"])
                                                     if q["score"] is not None else "unknown"))
        doc.p(R("What management's decisions left in the numbers -- returns on the capital it "
                "controls, what it did with the share count, how much it paid for acquisitions, "
                "how it runs the balance sheet, whether reported profit turns into cash, what "
                "insiders do with their own money, and how reliably it meets expectations. "
                "%d of 100 points measured%s." % (q["measured"], "" if q["measured"] == 100 else
                "; unmeasured parts are left out and the rest re-scaled, never scored as zero"),
                color=INK2, size=9))
        qrows = [["Component", "Weight", "Score", "Evidence"]]
        qcol = {}
        for i, c in enumerate(q["components"], 1):
            val = c["value"]
            qrows.append([c["label"], "%d" % c["weight"],
                          "n/m" if val is None else "%.0f%%" % (100 * val), c["text"]])
            if val is not None:
                qcol[(i, 2)] = GREEN if val >= 0.7 else (YELLOW if val >= 0.4 else RED)
        doc.table(qrows, [2600, 900, 1000, 5580], align=["left", "right", "right", "left"], colors=qcol)
        doc.p(R("n/m = not measured (no data, or not meaningful for this kind of company).", color=INK3, size=8))
    doc.p([R("Competitive position: ", bold=True),
           R("not assessed from data -- the Unusual Whales payload carries no market-share or "
             "customer-concentration fields. Treat this as an open question, not a pass.", color=INK2)])

    # 4 ---------------------------------------------------------- FCF
    doc.h1("4. Free Cash Flow Analysis")
    doc.table([["", "Amount", "% of revenue"],
               ["Operating cash flow", V.money(f["ocf"]), V.pct(V.safe_div(f["ocf"], f["revenue"]))],
               ["Capital expenditure", V.money(f["capex"]), V.pct(f["capex_intensity"])],
               ["Free cash flow (OCF - capex)", V.money(f["fcf"]), V.pct(f["fcf_margin"])],
               ["Owner FCF (OCF - maintenance capex)", V.money(f["owner_fcf"]), V.pct(f["owner_margin"])],
               ["Stock-based compensation", V.money(f["sbc"]), V.pct(f["sbc_pct"])],
               ["Dividends paid", V.money(f["dividends"]), ""],
               ["Buybacks", V.money(f["buybacks"]), ""]],
              [4400, 2840, 2840], align=["left", "right", "right"])
    if res["runway_years"] is not None:
        doc.p([R("Cash runway: ", bold=True),
               R("%s of cash and short-term investments against %s a year of burn = %.1f years. "
                 % (V.money(f["liquid"]), V.money(-f["fcf"]), res["runway_years"])),
               R("Cumulative base-case cash flow bottoms at %s before turning positive."
                 % V.money(b["min_cum"]))])
    elif f["fcf"] is not None:
        doc.p("Maintenance capex is approximated by depreciation & amortisation (never more than "
              "actual capex). Capex above D&A is treated as growth investment: the base case "
              "values owner earnings, the bear case charges the full capex.")
    long_hist = f.get("margin_hist_long") or []
    if len(long_hist) > len(f["margin_hist"] or []):
        # 3.1: up to 10 years; the DCF's base margin still leans on the latest 3
        doc.h2("Cash margin history (%d years)" % len(long_hist))
        doc.table([["Fiscal year", "Revenue", "Reported FCF", "Owner FCF", "Owner - SBC"]] +
                  [[h["fy"], V.money(h.get("rev")), V.pct(h.get("rep")), V.pct(h.get("own")), V.pct(h.get("adj"))]
                   for h in long_hist],
                  [1680, 2100, 2100, 2100, 2100], align=["left", "right", "right", "right", "right"])
    elif f["margin_hist"]:
        doc.h2("Cash margin history")
        doc.table([["Fiscal year", "Reported FCF margin", "Owner FCF margin"]] +
                  [[h["fy"], V.pct(h["rep"]), V.pct(h["own"])] for h in f["margin_hist"]],
                  [3360, 3360, 3360], align=["left", "right", "right"])
    rule = f.get("_margin_rule")
    if rule:
        doc.p([R("Base-case margin: ", bold=True), R({
            "midpoint": "midpoint of today's and the 3-year average SBC-adjusted cash margin.",
            "trend": "TODAY's SBC-adjusted margin -- three straight years of rising margin and revenue "
                     "(trend rule), so the base is not anchored to a weaker past.",
            "cycle": "blend of the 10-year median and the 3-year midpoint (cycle rule).",
        }[rule])])
    cyc = res["valuation"].get("cycle") or {}
    if cyc.get("known"):
        if cyc.get("cyclical"):
            ctext = ("Cyclical by its own %d-year history (revenue fell in %d yr(s), margin dropped >5 pts in %d). "
                     "10-yr median SBC-adjusted margin %s (sd %s). "
                     % (cyc["years"], cyc["rev_down_years"], cyc["margin_drops"],
                        V.pct(cyc["median_adj"]), V.pct(cyc["sd_adj"])))
            ctext += ("This check changes the value." if (res["valuation"].get("options") or {}).get("cycle_aware")
                      else "Shown as a warning only -- it does not change the value or score.")
        else:
            ctext = "Not cyclical by its own %d-year history." % cyc["years"]
        doc.p([R("Cycle check: ", bold=True), R(ctext)])

    # 5 ---------------------------------------------------- balance sheet
    doc.h1("5. Balance Sheet & Financial Strength")
    lev = None
    if f["debt"] is not None and f["ebitda"] and f["ebitda"] > 0:
        lev = (f["debt"] - (f["liquid"] or 0)) / f["ebitda"]
    doc.table([["Item", "Value"],
               ["As of", f["bs_date"] or "not available"],
               ["Cash + short-term investments", V.money(f["liquid"])],
               ["Total debt (incl. leases)", V.money(f["debt"])],
               ["Net cash (debt)", V.money(f["net_cash"])],
               ["Shareholder equity", V.money(f["equity"])],
               ["Goodwill + intangibles", V.money(f["goodwill_intang"])],
               ["Net debt / EBITDA", "n/m" if lev is None else "%.1fx" % lev],
               ["Current ratio", V.mult(V.safe_div(f["current_assets"], f["current_liabilities"]))]],
              [5040, 5040], align=["left", "right"])
    if res["class"] == "financial":
        doc.p("For a bank or insurer, cash and debt are operating assets and liabilities, not "
              "financing: the valuation adds no net-cash adjustment.")

    # 6 ---------------------------------------------------------- multiples
    doc.h1("6. Valuation Multiples")
    ref = m["sector_ref"] or {}
    doc.table([["Multiple", f["ticker"], "Sector reference*"],
               ["P/E", V.mult(m["pe"]) if m["pe_meaningful"] else "n/m (operating loss)",
                "%sx" % ref["pe"] if ref.get("pe") else "n/a"],
               ["P/S", V.mult(m["ps"]), "%sx" % ref["ps"] if ref.get("ps") else "n/a"],
               ["Price / FCF", V.mult(m["pfcf"]), ""],
               ["FCF yield", V.pct(m["fcf_yield"]), ""],
               ["EV / EBITDA", V.mult(m["ev_ebitda"]), "%sx" % ref["ev_ebitda"] if ref.get("ev_ebitda") else "n/a"],
               ["Price / book", V.mult(m["pb"]), ""]],
              [3360, 3360, 3360], align=["left", "right", "right"])
    doc.p(R("*Sector references are static typical large-cap medians built into the desk, not "
            "live data. They frame the multiple; they do not drive the verdict.", italic=True,
            color=INK3, size=9))

    # 7 ---------------------------------------------------------- DCF
    doc.h1("7. DCF Valuation Model")
    doc.p([R("Model: ", bold=True), R("%s -- %s. " % (res["class_label"], res["method"])),
           R(res["class_reason"])])
    doc.table([["Assumption", "Value"],
               ["Discount rate", "%.1f%% -- %s" % (100 * v["discount"], v["discount_how"])],
               ["Projection period", "%d years: %d at the scenario growth rate, then %d fading to "
                "the terminal rate (fade starts from at most %.0f%%)"
                % (V.YEARS + V.FADE_YEARS, V.YEARS, V.FADE_YEARS, 100 * V.FADE_START_CAP)],
               ["Growth funding", (v["capital"]["how"] + ("" if v["capital"].get("from_year", 1) == 1 else
                                  " -- charged from year %d; before that the reported cash burn already "
                                  "includes capex" % v["capital"]["from_year"]))],
               ["Growth band", "%s, positioned at %.0f%% by trailing revenue growth of %s"
                % (v["band"], 100 * v["band_pos"], V.signed_pct(f["rev_growth"]))],
               ["Terminal growth", "bull 3.0% / base 2.5% / bear 2.0%"],
               ["Terminal value", "Year-10 earnings x (1 + g), less the investment that growth needs, / (r - g); "
                "zero if year-10 earnings are negative"],
               ["Equity value", "Enterprise value + net cash" + (" (0 for financials)" if res["class"] == "financial" else "")]]
              + ([["Overrides", ", ".join("%s = %s" % kv for kv in sorted(res["overrides"].items()))]]
                 if res.get("overrides") else []),
              [2600, 7480])
    doc.h2("Scenarios")
    srows = [["Scenario", "Revenue growth", "Start margin", "Year-5 margin", "Equity value", "Per share", "vs price"]]
    scol = {}
    for i, k in enumerate(("bull", "base", "bear"), 1):
        x = sc[k]
        srows.append([k.capitalize(), V.pct(x["growth"]), V.pct(x["m0"]), V.pct(x["m5"]),
                      V.money(x["equity"]), V.px(x["per_share"]) + (" (floored)" if x["floored"] else ""),
                      V.signed_pct(x["upside"])])
        scol[(i, 6)] = GREEN if (x["upside"] or 0) >= 0 else RED
    doc.table(srows, [1300, 1400, 1360, 1400, 1640, 1600, 1380],
              align=["left"] + ["right"] * 6, colors=scol)
    doc.h2("Base case, year by year")
    doc.table([["Year", "Growth", "Revenue", "Margin", "Reinvested", "Cash flow", "Present value"]] +
              [["Y%d" % r["year"], V.pct(r["growth"]), V.money(r["revenue"]), V.pct(r["margin"]),
                V.money(r["reinvest"]), V.money(r["cf"]), V.money(r["pv"])]
               for r in b["rows"]] +
              [["Terminal", "", "", "", "", V.money(b["tv"]), V.money(b["pv_tv"])],
               ["Net cash", "", "", "", "", "", V.money(v["net_cash_used"])],
               ["Equity", "", "", "", "", "", V.money(b["equity"])]],
              [1100, 1200, 1500, 1200, 1600, 1700, 1780], align=["left"] + ["right"] * 6)
    if b["tv_share"] is not None:
        doc.p("Terminal value is %s of base-case enterprise value%s." % (
            V.pct(b["tv_share"]), " (years 1-5 are net cash-negative)" if b["pv_cf"] < 0 else ""))
    er = v.get("returns")
    if er:
        doc.h2("What a 5-10 year holder earns")
        doc.table([["If you buy at %s and ..." % V.px(f["price"]), "Annual return"],
                   ["the price reaches the base value by year 5", _pctn(er["irr"].get(5) if er["irr"] else None)],
                   ["the price reaches the base value by year 10", _pctn(er["irr"].get(10) if er["irr"] else None)],
                   ["the price never re-rates (you earn the business's cash flows)", _pctn(er.get("implied_return"))],
                   ["For comparison: the required return used in this DCF", _pctn(v["discount"])]],
                  [7000, 3080], align=["left", "right"])
        ig = er.get("implied_growth")
        doc.p([R("Reverse DCF: ", bold=True),
               R(("today's price assumes about %s revenue growth a year for five years (with this "
                  "model's margins, fade and reinvestment), against %s in the base case."
                  % (V.pct(ig), V.pct(b["growth"]))) if ig is not None else
                 ("no growth rate in the tested range reproduces today's price. " + " ".join(er.get("notes") or [])))])
        doc.p(R("Returns include the cash flow the business generates each year as if it were "
                "paid out. They are the base case's arithmetic, not a forecast of the share price.",
                color=INK2, size=9))

    # 8 ---------------------------------------------------------- risks
    doc.h1("8. Risk Assessment")
    bad = [x for x in res["flags"] if x["bad"]]
    good = [x for x in res["flags"] if not x["bad"]]
    if bad:
        doc.h2("Red flags")
        for x in bad:
            doc.bullet(R("%s%s" % (x["text"], "  (-%.2f from score)" % x["points"] if x["points"] else "")),
                       mark="✗", color=RED)
    if good:
        doc.h2("Checks passed")
        for x in good:
            doc.bullet(R(x["text"]), mark="✓", color=GREEN)
    doc.h2("Not measurable from this data")
    for u in res["unmeasured"]:
        doc.bullet(R(u, color=INK2), mark="?", color=INK3)
    doc.h2("Market risks")
    doc.bullet(R("Beta of %s: %s" % ("n/a" if f["beta"] is None else "%.2f" % f["beta"],
                 "moves more than the market" if (f["beta"] or 1) > 1.2 else "roughly market-like")))
    doc.bullet(R("Multiple compression: the verdict assumes a %.1f%% required return; every point "
                 "higher lowers the base value." % (100 * v["discount"])))
    for q in f["quality"] + f["notes"]:
        doc.bullet(R(q, color=INK2), mark="!", color=YELLOW)

    # 9 ---------------------------------------------------- recommendation
    doc.h1("9. Investment Recommendation")
    doc.table([["Verdict", "%d/10 %s (%s)" % (s["badge"], s["verdict"], res["stance"])],
               ["Score build", "valuation %.2f - red flags %.2f = %.1f%s" % (
                   s["valuation_points"], s["flag_points"], s["score"],
                   "; " + "; ".join(s["structural"]) if s["structural"] else "")],
               ["Position sizing", res["sizing"]],
               ["Suitable for", res["suitable"]]],
              [2600, 7480], header=False, bold_first_col=True, colors={(0, 1): col})
    gates = s.get("gates") or []
    if gates:
        doc.h2("Buffett gates")
        for g in gates:
            mark, c = ("✓", GREEN) if g["passed"] else ("✗", RED)
            doc.bullet(R("%s -- %s%s" % (g["rule"], g["value"],
                                          "  (APPLIED: score capped at %.1f)" % g["cap"] if g.get("applied") else "")),
                       mark=mark, color=c)
    doc.p([R("Scale: ", bold=True, color=INK2),
           R("10 = deeply undervalued, 0 = avoid. 8-10 strong buy, 6-7 buy, 4-5 hold, 2-3 reduce, "
             "0-1 avoid. Valuation points = 5 + 5 x base-case upside (so +100%% scores 10, fair "
             "value 5, -100%% scores 0). Red flags only ever subtract, capped at %.0f points. "
             "Then the Buffett gates: BUY or better needs a %d%% margin of safety AND quality 4+; "
             "STRONG BUY needs quality 6+. A gate can only lower the score, and says so."
             % (V.FLAG_POINTS_CAP, round(100 * V.MARGIN_OF_SAFETY)), color=INK2, size=9)])

    # 10 --------------------------------------------------------- watch
    doc.h1("10. Watch Metrics")
    for w in res["watch"]:
        doc.bullet(R(w), mark="☐")

    # 11 --------------------------------------------------------- disclaimer
    doc.h1("11. Disclaimer")
    doc.p(R("This report is generated automatically for educational purposes and is not financial "
            "advice, a recommendation, or an offer to buy or sell any security. A DCF is only as good "
            "as its assumptions, every one of which is stated above and can be changed. Financial data "
            "from the Unusual Whales API as of %s (statements to %s); it may contain errors or be "
            "incomplete. Do your own research and consult a licensed professional before investing."
            % (stamp, f["period_end"]), color=INK2, size=9))
    doc.p(R("Generated by %s, model %s. Data: Unusual Whales API. Reproduce with %s."
            % (desk, V.MODEL_VERSION, names(f["ticker"])["py"]), color=INK3, size=8))
    return doc.save(path)


def _pctn(x):
    return "n/a" if x is None else V.signed_pct(x)


def _insight(res):
    f, b = res["fin"], res["valuation"]["scenarios"]["base"]
    if res["class"] in ("venture", "growth_burn"):
        return ("The market price needs the bull case: at %s the stock sits %s the bull value of %s, "
                "and the base case requires %s of funding beyond today's cash."
                % (V.px(f["price"]),
                   "above" if (res["valuation"]["scenarios"]["bull"]["upside"] or 0) < 0 else "below",
                   V.px(res["valuation"]["scenarios"]["bull"]["per_share"]),
                   V.money(max(0.0, -(b["min_cum"]) - (f["liquid"] or 0)))))
    implied = None
    for g in [x / 1000 for x in range(-100, 1001, 5)]:
        fin2 = dict(f, rev_growth=g)
        try:
            val = V.value(fin2, res["class"])
        except Exception:
            break
        if val["scenarios"]["base"]["per_share"] and val["scenarios"]["base"]["per_share"] >= f["price"]:
            implied = val["scenarios"]["base"]["growth"]
            break
    if implied is None:
        return ("No growth rate inside this model's bands justifies %s: even the top of the band "
                "leaves the base case short of the price." % V.px(f["price"]))
    return ("To justify %s the base case would need about %s revenue growth for five years, against "
            "%s trailing." % (V.px(f["price"]), V.pct(implied, 0), V.signed_pct(f["rev_growth"])))


# ------------------------------------------------------------------ card

def _explain(res):
    """
    The card's method sentence. Must cope with runs saved by OLDER models:
    the history panel re-opens them, and 1.x/2.x results have no "capital"
    block and used a 5-year projection. (Model 3.0 first shipped reading
    v["capital"] unconditionally -> KeyError on the desk's opening page.)
    """
    v, sc = res["valuation"], res["valuation"]["scenarios"]
    cap = v.get("capital")
    years = v.get("years", 5)
    if years > 5:
        horizon = "%d-year projection (5 years at the scenario rate, %d fading)" % (years, years - 5)
    else:
        horizon = "5-year projection"
    if cap is None:
        funding = ""
    elif cap.get("kind") == "roe":
        funding = "growth funded at ROE %.0f%%, " % (100 * cap["value"])
    else:
        funding = "growth funded at sales-to-capital %.1f%s, " % (
            cap["value"], "" if cap.get("from_year", 1) == 1 else " from year %d" % cap["from_year"])
    return ("%s. Discount rate %.1f%%, %s, %sterminal growth 2.5%% (base). Base case grows revenue "
            "%s a year; %s." % (res["method"], 100 * v["discount"], horizon, funding,
                                V.pct(sc["base"]["growth"], 0), res.get("key_driver", "")))


def card(res):
    """Everything the canvas needs, and nothing it would have to derive."""
    f, v, s = res["fin"], res["valuation"], res["score"]
    sc = v["scenarios"]
    growth_lbl = "Revenue growth"
    ratio_lbl, ratio = ("P/E", V.mult(res["multiples"]["pe"])) if res["multiples"]["pe_meaningful"] \
        else ("P/S", V.mult(res["multiples"]["ps"]))
    if res["class"] == "financial":
        # FCF yield is meaningless for a bank (a large bank's can print deeply negative); net margin is not
        cash_lbl, cash = "Net margin", V.pct(f["net_margin"])
    elif res["runway_years"] is not None:
        cash_lbl, cash = "Cash runway", "%.1f yrs" % res["runway_years"]
    else:
        cash_lbl, cash = "FCF yield", V.pct(res["multiples"]["fcf_yield"])
    return {
        "ticker": f["ticker"], "name": f["name"], "sector": f["sector"],
        "class_label": res["class_label"], "method": res["method"],
        "badge": s["badge"], "score": s["score"], "score_uncapped": round(s["valuation_points"] - s["flag_points"], 2), "verdict": s["verdict"], "colour": s["colour"],
        "stance": res["stance"], "verdict_line": res["verdict_line"], "thesis": res["thesis"],
        "price": V.px(f["price"]), "marketcap": V.money(f["marketcap"]),
        "metrics": [
            ["Price", V.px(f["price"]), None],
            [growth_lbl, V.signed_pct(f["rev_growth"]), "good" if (f["rev_growth"] or 0) > 0 else "bad"],
            ["Intrinsic value (base)", V.px(sc["base"]["per_share"]), None],
            ["Operating margin", V.pct(f["op_margin"]), "good" if (f["op_margin"] or 0) > 0 else "bad"],
            ["Upside / downside", V.signed_pct(sc["base"]["upside"]),
             "good" if (sc["base"]["upside"] or 0) >= 0 else "bad"],
            [cash_lbl, cash, None],
            ["Market cap", V.money(f["marketcap"]), None],
            [ratio_lbl, ratio, None],
        ],
        "scenarios": [{"name": k.upper(), "value": V.px(sc[k]["per_share"]),
                       "upside": "net debt > value" if sc[k]["floored"] else V.signed_pct(sc[k]["upside"]),
                       "growth": V.pct(sc[k]["growth"], 0), "up": (sc[k]["upside"] or 0) >= 0,
                       "per_share": sc[k]["per_share"]}
                      for k in ("bull", "base", "bear")],
        "price_num": f["price"],
        "bullets": [{"bad": b["bad"], "text": b["text"]} for b in res["card_bullets"]],
        "carried_by": s["carried_by"][:3],
        "valuation_points": s["valuation_points"], "flag_points": s["flag_points"],
        "explain": _explain(res),
        "summary": [
            ["Business quality", "%s revenue, %s YoY, operating margin %s." % (
                V.money(f["revenue"]), V.signed_pct(f["rev_growth"]), V.pct(f["op_margin"]))],
            ["Valuation", "Base %s vs %s price (%s); bull %s, bear %s." % (
                V.px(sc["base"]["per_share"]), V.px(f["price"]), V.signed_pct(sc["base"]["upside"]),
                V.px(sc["bull"]["per_share"]), V.px(sc["bear"]["per_share"]))],
            ["Philosophy", "Intrinsic value from cash the business can return, with every "
                           "assumption stated. Red flags only ever subtract."],
        ],
        "basis": f["basis"], "overrides": res.get("overrides") or {},
        "model_version": res["model_version"],
        "quality": _card_quality(res),
        "returns": _card_returns(res),
        "gates": [{"key": g["key"], "passed": g["passed"], "applied": g.get("applied", False),
                   "value": g["value"]} for g in (s.get("gates") or [])],
        "why": _card_why(res),
        "synopsis": _synopsis(res),
    }


def _synopsis(res):
    """Stored runs made before the synopsis existed get one computed now, when possible."""
    if res.get("synopsis"):
        return res["synopsis"]
    try:
        return V.synopsis(res)
    except Exception:
        return ""


def _card_quality(res):
    q = res.get("quality")
    if not q:
        return None                       # a run saved before model 3.2
    return {"score": q["score"], "tier": q["tier"], "measured": q["measured"],
            "parts": [[c["label"], c["value"]] for c in q["components"]]}


def _card_returns(res):
    er = (res.get("valuation") or {}).get("returns")
    if not er:
        return None
    irr = er.get("irr") or {}
    g = lambda k: irr.get(k) if k in irr else irr.get(str(k))    # JSON round-trip turns keys into str
    return {"irr5": g(5), "irr10": g(10), "implied_return": er.get("implied_return"),
            "implied_growth": er.get("implied_growth"), "discount": res["valuation"]["discount"]}


def _card_why(res):
    """The one sentence that explains a gated verdict, else the first gate status."""
    lines = res.get("why") or []
    for l in lines:
        if "caps this" in l or "FAILS" in l:
            return l
    return lines[1] if len(lines) > 1 else (lines[0] if lines else "")
